// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxzbjyjgpqatoipkpnrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4emJqeWpncHFhdG9pcGtwbnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzU2MTcsImV4cCI6MjA1NjA1MTYxN30.ZS0GXozTMPfahIkB0EZiltoFmXjd2ah-bVfYd3M7d4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);